### ISSUE TITLE
Live Reload

### ISSUE THREAD

**Issue by zek** [websemantics/strong-together#1]
Hi I'm really beginner for these stuff and trying to learn it.

I would like to ask how can I make fast development? 

Everytime I change any line of code I have to "npm run build".

What do you suggest me for it?

**Comment by websemantics** [comment]
Hi @drtzack ,
I added a new script `npm run watch` that monitors any changes inside `resources` folder and run build script. This should work for now until I optimize the build process for faster builds,
Hope that helps,

**Comment by zek** [comment]
Thanks! 👍
